# This workflow is meant to generate the slides markdown file slides.md in the x folder.

name: slideGen

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh-pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: slideGen script
        run: python3 slideGen.py
      
      - name: config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
        
      - name: push 
        run: |
          git add slides.md
          git commit -m "updated version of slides"
          git push origin master
